//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.05.17 at 01:37:32 PM EEST
//

package com.classroom.services.web.controllers.wadl.artifact;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.mine.wadl.artifact package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class WadlObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.mine.wadl.artifact
     * 
     */
    public WadlObjectFactory() {
    }

    /**
     * Create an instance of {@link WadlResources }.
     * 
     * @return the wadl resources
     */
    public WadlResources createResources() {
        return new WadlResources();
    }

    /**
     * Create an instance of {@link WadlDoc }.
     * 
     * @return the wadl doc
     */
    public WadlDoc createDoc() {
        return new WadlDoc();
    }

    /**
     * Create an instance of {@link WadlResource }.
     * 
     * @return the wadl resource
     */
    public WadlResource createResource() {
        return new WadlResource();
    }

    /**
     * Create an instance of {@link WadlParam }.
     * 
     * @return the wadl param
     */
    public WadlParam createParam() {
        return new WadlParam();
    }

    /**
     * Create an instance of {@link WadlOption }.
     * 
     * @return the wadl option
     */
    public WadlOption createOption() {
        return new WadlOption();
    }

    /**
     * Create an instance of {@link WadlLink }.
     * 
     * @return the wadl link
     */
    public WadlLink createLink() {
        return new WadlLink();
    }

    /**
     * Create an instance of {@link WadlMethod }.
     * 
     * @return the wadl method
     */
    public WadlMethod createMethod() {
        return new WadlMethod();
    }

    /**
     * Create an instance of {@link WadlRequest }.
     * 
     * @return the wadl request
     */
    public WadlRequest createRequest() {
        return new WadlRequest();
    }

    /**
     * Create an instance of {@link WadlRepresentation }.
     * 
     * @return the wadl representation
     */
    public WadlRepresentation createRepresentation() {
        return new WadlRepresentation();
    }

    /**
     * Create an instance of {@link WadlResponse }.
     * 
     * @return the wadl response
     */
    public WadlResponse createResponse() {
        return new WadlResponse();
    }

    /**
     * Create an instance of {@link WadlApplication }.
     * 
     * @return the wadl application
     */
    public WadlApplication createApplication() {
        return new WadlApplication();
    }

    /**
     * Create an instance of {@link WadlGrammars }.
     * 
     * @return the wadl grammars
     */
    public WadlGrammars createGrammars() {
        return new WadlGrammars();
    }

    /**
     * Create an instance of {@link WadlInclude }.
     * 
     * @return the wadl include
     */
    public WadlInclude createInclude() {
        return new WadlInclude();
    }

    /**
     * Create an instance of {@link WadlResourceType }.
     * 
     * @return the wadl resource type
     */
    public WadlResourceType createResourceType() {
        return new WadlResourceType();
    }

}
